### ISSUE TITLE
非系统盘的浏览器如何修改检索路径？

### ISSUE THREAD

**Issue by M142857** [hhelibeb/Wox.Plugin.Firefox-Bookmarks#1]
如题。浏览器Centbrowser，安装在D盘，使用ff插件时无反应，提示：set up the 'db_path' in your config.json in the plugin dir。

修改config.json，"db_path": "D://centbrowser_4.2.10.171_x64_portable/User Data", 依然无反应。

在其他插件修改os.path.abspath('D://centbrowser_4.2.10.171_x64_portable/User Data/Default/Bookmarks')，可以使用。

请问非系统盘的浏览器如何修改检索路径？

**Comment by hhelibeb** [comment]
额 好久前弄的，我没有一直用它，没记错的话只支持firefox，不支持cent
